import { describe, expect, it } from "vitest";
import { parseFilters } from "@/lib/faculty/filters";
import { buildDirectoryReport, parseReportFormat } from "../export";
import { directoryPdfResponse } from "../export-formats";
import type { DirectoryRow } from "@/lib/queries/directory";

/**
 * The exports are files somebody prints or opens in a spreadsheet, so a type
 * error is not the failure mode to worry about — a structurally invalid file
 * is. These assert the PDF's magic bytes, and that the provenance the report
 * promises (who, when, which filters) actually reaches the model both formats
 * render from.
 */

const FILTERS = parseFilters({ department: "AIML", semester: "1" });

function student(over: Partial<DirectoryRow> = {}): DirectoryRow {
  return {
    id: "s1",
    fullName: "Aisha R",
    usn: "1HK24AI001",
    email: "a@hkbk.edu.in",
    phone: "9000000001",
    departmentCode: "AIML",
    city: "Bengaluru",
    state: "Karnataka",
    semester: 1,
    section: "A",
    quota: "cet",
    residenceType: "hostel",
    tenthPercentage: 90,
    twelfthPercentage: 88,
    entranceRank: 1200,
    completionPercent: 100,
    guardianName: null,
    guardianPhone: null,
    guardianVisible: false,
    photoPath: null,
    photoUrl: null,
    ...over,
  };
}

const INPUT = {
  rows: [student(), student({ id: "s2", fullName: "Bilal K", usn: "1HK24AI002" })],
  filters: FILTERS,
  generatedBy: "Prof X (EMP1)",
  scopeNote: "Department: AIML",
  filenamePrefix: "aiml-students",
};

describe("buildDirectoryReport", () => {
  it("records who exported, when, the scope, and the filters applied", () => {
    const report = buildDirectoryReport(INPUT);
    const meta = Object.fromEntries(report.meta);

    expect(meta["Generated by"]).toBe("Prof X (EMP1)");
    expect(meta["Scope"]).toBe("Department: AIML");
    expect(meta["Rows"]).toBe("2");
    // The filters are the point of the header — a file detached from the
    // query that made it is indistinguishable from a stale one.
    expect(meta["Filters applied"]).toContain("AIML");
    expect(meta["Generated at"]).toMatch(/^\d{4}-\d{2}-\d{2}T/);
  });

  it("says so plainly when no filter was applied", () => {
    const report = buildDirectoryReport({ ...INPUT, filters: parseFilters({}) });
    expect(Object.fromEntries(report.meta)["Filters applied"]).toBe("None");
  });

  it("puts one row per student under a header row", () => {
    const report = buildDirectoryReport(INPUT);
    expect(report.columns[0]).toBe("Full name");
    expect(report.data).toHaveLength(2);
    expect(report.data[0][0]).toBe("Aisha R");
  });

  it("masks guardian contact the exporter is not entitled to", () => {
    const report = buildDirectoryReport(INPUT);
    const guardianIndex = report.columns.indexOf("Guardian name");
    expect(report.data[0][guardianIndex]).toBe("(not permitted)");
  });
});

describe("parseReportFormat", () => {
  it("accepts the two offered formats", () => {
    expect(parseReportFormat("pdf")).toBe("pdf");
    expect(parseReportFormat("csv")).toBe("csv");
  });

  it("falls back to csv rather than throwing on anything else", () => {
    expect(parseReportFormat(null)).toBe("csv");
    expect(parseReportFormat("exe")).toBe("csv");
  });

  it("still answers an old xlsx link with the CSV Excel can open", () => {
    // The Excel renderer was removed; a bookmarked link must not 500.
    expect(parseReportFormat("xlsx")).toBe("csv");
  });
});

describe("file output", () => {
  it("writes a real pdf", async () => {
    const response = directoryPdfResponse(INPUT);
    const text = new TextDecoder().decode(await response.arrayBuffer());

    expect(text.startsWith("%PDF-")).toBe(true);
    expect(response.headers.get("Content-Type")).toBe("application/pdf");
    expect(response.headers.get("Content-Disposition")).toContain(".pdf");
  });

  it("forbids caching the file — it carries personal data", () => {
    const response = directoryPdfResponse(INPUT);
    expect(response.headers.get("Cache-Control")).toBe("no-store, private");
  });
});
