import { NextResponse } from "next/server";
import { describeFilters, toCsv, type StudentFilters } from "@/lib/faculty/filters";
import { SUM_DISCLAIMER, SUM_LABEL, type MarkComponent } from "@/config/marks";
import type { MarksExportRow } from "@/lib/queries/marks";
import type { DirectoryRow } from "@/lib/queries/directory";

/**
 * CSV export of internal marks (PRD 5.11, migration 0025).
 *
 * One row per student per subject, with a column per component — the same
 * shape as the grid on screen, so a member of staff can compare the file to
 * the page they exported it from without mentally transposing anything. The
 * component columns are generated from `mark_components`, so a college that
 * adds IA3 gets a new column rather than a code change.
 *
 * Two rules carried over from the screens, because a spreadsheet outlives the
 * page that made it and will be read by someone who never saw the UI:
 *
 *  1. The total is labelled as the sum of recorded components, and the
 *     disclaimer travels in the header. A column called "CIE" in a file
 *     emailed to a registrar is exactly the false authority this feature is
 *     built to avoid.
 *  2. A blank cell means not marked. It is never a zero, and the
 *     "Unreleased components" column names anything the student cannot see,
 *     so a figure here is never mistaken for one they have been given.
 */
export function marksCsvResponse({
  rows,
  students,
  components,
  filters,
  generatedBy,
  scopeNote,
  filenamePrefix = "internal-marks",
}: {
  rows: MarksExportRow[];
  /** The directory rows, for names and USNs. */
  students: DirectoryRow[];
  components: MarkComponent[];
  filters: StudentFilters;
  generatedBy: string;
  scopeNote: string;
  filenamePrefix?: string;
}): NextResponse {
  const generatedAt = new Date().toISOString();
  const applied = describeFilters(filters);
  const studentById = new Map(students.map((s) => [s.id, s]));

  const header: Array<Array<unknown>> = [
    ["First-Year Portal — internal marks export"],
    ["Generated by", generatedBy],
    ["Generated at", generatedAt],
    ["Scope", scopeNote],
    ["Filters applied", applied.length > 0 ? applied.join("; ") : "None"],
    ["Rows", rows.length],
    ["Note", SUM_DISCLAIMER],
    [],
  ];

  const table: Array<Array<unknown>> = [
    [
      "Full name",
      "USN",
      "Department",
      "Semester",
      "Section",
      "Subject code",
      "Subject",
      ...components.map((c) => `${c.label} (out of ${c.maxMarks})`),
      SUM_LABEL,
      "Out of",
      "Unreleased components",
    ],
    ...rows
      // A marks row whose student is outside the filtered set is dropped
      // rather than exported without a name attached to it.
      .filter((row) => studentById.has(row.studentId))
      .map((row) => {
        const student = studentById.get(row.studentId)!;
        return [
          student.fullName,
          student.usn,
          student.departmentCode,
          row.semester,
          student.section,
          row.subjectCode,
          row.subjectName,
          ...components.map((component) => {
            const cell = row.byComponent.get(component.code);
            // Empty, not 0 — see rule 2 above.
            return cell && cell.marks !== null ? cell.marks : "";
          }),
          row.scored,
          row.outOf,
          row.unreleased.length > 0 ? row.unreleased.join("; ") : "",
        ];
      }),
  ];

  const filename = `${filenamePrefix}-${generatedAt.slice(0, 10)}.csv`;

  return new NextResponse(toCsv([...header, ...table]), {
    headers: {
      "Content-Type": "text/csv; charset=utf-8",
      "Content-Disposition": `attachment; filename="${filename}"`,
      // Student personal data — never let a proxy or the browser keep a copy.
      "Cache-Control": "no-store, private",
    },
  });
}
