import { NextResponse, type NextRequest } from "next/server";
import {
  getOwnFaculty,
  listAllStudentsForExport,
} from "@/lib/queries/faculty";
import { describeFilters, parseFilters, toCsv } from "@/lib/faculty/filters";
import { residenceLabel } from "@/config/residence";

/**
 * CSV export of the current filtered view (PRD 5.5, 5.11).
 *
 * The file carries a provenance header — who exported it, when, and which
 * filters were applied — because these files get emailed around and detached
 * from the query that produced them (PRD 5.11 requires exactly this).
 *
 * Guardian columns come from `student_directory`, so they are already NULL
 * for students this faculty member does not mentor. The export cannot leak
 * what the screen would not show.
 */
export async function GET(request: NextRequest) {
  const faculty = await getOwnFaculty();
  if (!faculty) {
    return new NextResponse("Not authorised", { status: 403 });
  }

  const raw = Object.fromEntries(request.nextUrl.searchParams.entries());
  const filters = parseFilters(raw);
  const rows = await listAllStudentsForExport(filters);

  const applied = describeFilters(filters);
  const generatedAt = new Date().toISOString();

  const header: Array<Array<unknown>> = [
    ["First-Year Portal — student export"],
    ["Generated by", `${faculty.fullName} (${faculty.employeeCode})`],
    ["Generated at", generatedAt],
    ["Filters applied", applied.length > 0 ? applied.join("; ") : "None"],
    ["Rows", rows.length],
    [],
  ];

  const table: Array<Array<unknown>> = [
    [
      "Full name",
      "USN",
      "Email",
      "Phone",
      "Department",
      "Semester",
      "Section",
      "Quota",
      "Entrance rank",
      "10th %",
      "12th %",
      "Residence type",
      "Profile completion %",
      "Guardian name",
      "Guardian phone",
    ],
    ...rows.map((student) => [
      student.fullName,
      student.usn,
      student.email,
      student.phone,
      student.departmentCode,
      student.semester,
      student.section,
      student.quota,
      student.entranceRank,
      student.tenthPercentage,
      student.twelfthPercentage,
      residenceLabel(student.residenceType),
      student.completionPercent,
      student.guardianVisible ? student.guardianName : "(not mentor)",
      student.guardianVisible ? student.guardianPhone : "(not mentor)",
    ]),
  ];

  const csv = toCsv([...header, ...table]);
  const filename = `students-${generatedAt.slice(0, 10)}.csv`;

  return new NextResponse(csv, {
    headers: {
      "Content-Type": "text/csv; charset=utf-8",
      "Content-Disposition": `attachment; filename="${filename}"`,
      // This file contains student personal data — never let a proxy or the
      // browser keep a copy.
      "Cache-Control": "no-store, private",
    },
  });
}
