import { NextResponse } from "next/server";
import { describeFilters, toCsv, type StudentFilters } from "@/lib/faculty/filters";
import { residenceLabel } from "@/config/residence";
import type { DirectoryRow } from "@/lib/queries/directory";

/**
 * CSV export of a filtered directory view (PRD 5.5, 5.11).
 *
 * One builder for the faculty, HOD, and admin export routes. The file carries
 * a provenance header — who exported it, when, and which filters produced it —
 * because these files get emailed around and detached from the query that
 * made them; without the header, a stale export is indistinguishable from a
 * current one.
 *
 * Guardian columns come from `student_directory`, so they are already NULL for
 * students the exporter is not entitled to contact. The export cannot leak
 * what the screen would not show.
 */
export function directoryCsvResponse({
  rows,
  filters,
  generatedBy,
  scopeNote,
  filenamePrefix = "students",
}: {
  rows: DirectoryRow[];
  filters: StudentFilters;
  /** Name and code of the person exporting, for the provenance header. */
  generatedBy: string;
  /** One line stating whose students these are, e.g. "Department: AIML". */
  scopeNote: string;
  filenamePrefix?: string;
}): NextResponse {
  const generatedAt = new Date().toISOString();
  const applied = describeFilters(filters);

  const header: Array<Array<unknown>> = [
    ["First-Year Portal — student export"],
    ["Generated by", generatedBy],
    ["Generated at", generatedAt],
    ["Scope", scopeNote],
    ["Filters applied", applied.length > 0 ? applied.join("; ") : "None"],
    ["Rows", rows.length],
    [],
  ];

  const table: Array<Array<unknown>> = [
    [
      "Full name",
      "USN",
      "Email",
      "Phone",
      "Department",
      "Semester",
      "Section",
      "Quota",
      "Entrance rank",
      "10th %",
      "12th %",
      "Residence type",
      "City",
      "State",
      "Profile completion %",
      "Guardian name",
      "Guardian phone",
    ],
    ...rows.map((student) => [
      student.fullName,
      student.usn,
      student.email,
      student.phone,
      student.departmentCode,
      student.semester,
      student.section,
      student.quota,
      student.entranceRank,
      student.tenthPercentage,
      student.twelfthPercentage,
      residenceLabel(student.residenceType),
      student.city,
      student.state,
      student.completionPercent,
      student.guardianVisible ? student.guardianName : "(not permitted)",
      student.guardianVisible ? student.guardianPhone : "(not permitted)",
    ]),
  ];

  const filename = `${filenamePrefix}-${generatedAt.slice(0, 10)}.csv`;

  return new NextResponse(toCsv([...header, ...table]), {
    headers: {
      "Content-Type": "text/csv; charset=utf-8",
      "Content-Disposition": `attachment; filename="${filename}"`,
      // This file contains student personal data — never let a proxy or the
      // browser keep a copy.
      "Cache-Control": "no-store, private",
    },
  });
}
