import { NextResponse } from "next/server";
import { getAdminOverview, getOwnAdmin } from "@/lib/queries/admin";
import { toCsv } from "@/lib/faculty/filters";

/**
 * Institution-wide department report (PRD 5.6, 5.11).
 *
 * Aggregates only — no student rows. An admin who wants student-level data
 * should use the faculty directory export, which carries the guardian-masking
 * rules; duplicating that here would mean maintaining the masking logic twice.
 */
export async function GET() {
  const admin = await getOwnAdmin();
  if (!admin) {
    return new NextResponse("Not authorised", { status: 403 });
  }

  const { institution, departments, facultyCount, pendingAccounts } =
    await getAdminOverview();
  const generatedAt = new Date().toISOString();

  const rows: Array<Array<unknown>> = [
    ["First-Year Portal — institution report"],
    ["Generated by", `${admin.fullName} (${admin.employeeCode})`],
    ["Generated at", generatedAt],
    [],
    ["Total students", institution.totalStudents],
    ["Profiles complete", institution.complete],
    ["Profiles incomplete", institution.incomplete],
    ["Completion rate %", institution.completionRate],
    ["Average 10th %", institution.avgTenth ?? ""],
    ["Average 12th %", institution.avgTwelfth ?? ""],
    ["Faculty accounts", facultyCount],
    ["Accounts awaiting approval", pendingAccounts],
    [],
    ["Department", "Name", "Students", "Complete", "Completion %", "Avg 10th", "Avg 12th", "Living away", "Living at home"],
    ...departments.map((dept) => [
      dept.code,
      dept.name,
      dept.total,
      dept.complete,
      dept.completionRate,
      dept.avgTenth ?? "",
      dept.avgTwelfth ?? "",
      dept.livingAway,
      dept.livingAtHome,
    ]),
    [],
    ["Distribution", "Category", "Students"],
    ...institution.byQuota.map((s) => ["Quota", s.label, s.count]),
    ...institution.byResidence.map((s) => ["Residence type", s.label, s.count]),
    ...institution.bySemester.map((s) => ["Semester", s.label, s.count]),
    ...institution.byState.map((s) => ["Home state", s.label, s.count]),
  ];

  return new NextResponse(toCsv(rows), {
    headers: {
      "Content-Type": "text/csv; charset=utf-8",
      "Content-Disposition": `attachment; filename="institution-report-${generatedAt.slice(0, 10)}.csv"`,
      "Cache-Control": "no-store, private",
    },
  });
}
